apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server #Component can be any name - it's just a label
    spec:
      containers:
      - name: server
        image: sahanratnayake/multi-server
        ports:
        - containerPort: 5000

# Way to contain multiple objects in one file
---

apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
  - port: 5000
    targetPort: 5000
