apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistant-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # 1GB space
      